DotNetCampus.CommandLine.Help.UsageHeader = "Usage: "
DotNetCampus.CommandLine.Help.UsageOptions = "[options]"
DotNetCampus.CommandLine.Help.UsageCommand = "<command>"
DotNetCampus.CommandLine.Help.UsagePositionalArguments = "[arguments]"
DotNetCampus.CommandLine.Help.CommandHeader = "Commands:"
DotNetCampus.CommandLine.Help.OptionsHeader = "Options:"
DotNetCampus.CommandLine.Help.PositionalArgumentsHeader = "Arguments:"
DotNetCampus.CommandLine.Help.Required = "(required)"
DotNetCampus.CommandLine.Help.HelpDescription = "Show help information"
