DotNetCampus.CommandLine.Help.UsageHeader = "用法："
DotNetCampus.CommandLine.Help.UsageOptions = "[选项]"
DotNetCampus.CommandLine.Help.UsageCommand = "<命令>"
DotNetCampus.CommandLine.Help.UsagePositionalArguments = "[位置参数]"
DotNetCampus.CommandLine.Help.CommandHeader = "命令："
DotNetCampus.CommandLine.Help.OptionsHeader = "选项："
DotNetCampus.CommandLine.Help.PositionalArgumentsHeader = "位置参数："
DotNetCampus.CommandLine.Help.Required = "(必需)"
DotNetCampus.CommandLine.Help.HelpDescription = "显示帮助信息"
