name: NuGet Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-dotnet@v1
      - name: Pack
        run: dotnet build --configuration Release
      - name: Setup Nuget.exe
        uses: warrenbuckley/Setup-Nuget@v1
      - name: Add private GitHub registry to NuGet
        run: nuget sources add -name github -Source https://nuget.pkg.github.com/ORGANIZATION_NAME/index.json -Username ORGANIZATION_NAME -Password ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        run: |
          dotnet nuget push .\bin\Release\*.nupkg --skip-duplicate --source github
          dotnet nuget push .\bin\Release\*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NugetOrgDotnetCampusApiKey }} --no-symbols 1
